---
- name: Install mysql database
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server 
    - mysql-client 
    # Needed for ansible mysql commands
    - python-mysqldb

- name: copy .my.cnf file with root password credentials
  template: src=root-my-cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql.root_password }} login_user=root login_password={{ mysql.root_password }} check_implicit_admin=yes
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"

- name: remove the test database
  mysql_db: name=test state=absent
