---
- name: Install PHP packages 
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-fpm 
    - php5 
    - php5-cli 
    - php5-mysql 
    - php5-curl 
    - php5-gd 
  notify:
    - restart php5-fpm

- name: Upload the php5-fpm pool config file
  template: src=www.conf.j2 dest=/etc/php5/fpm/pool.d/www.conf
  notify:
    - restart php5-fpm