---
# Secure Linode - See https://library.linode.com/securing-your-server
- name: Create group based on 'admin.username' variable
  group: name={{ admin.username }} state=present

- name: Create user based on 'admin.username' variable
  user: name={{ admin.username }} password={{ admin.password }} state=present group={{ admin.username }} groups=sudo shell=/bin/bash

- name: Create .ssh folder in users home folder
  file: path=/home/{{ admin.username }}/.ssh state=directory recurse=yes owner={{ admin.username }} group={{ admin.username }} mode=0700

- name : Copy authorized SSH keys in place
  copy: src=ssh/authorized_keys dest=/home/{{ admin.username }}/.ssh/authorized_keys
          owner={{ admin.username }} group={{ admin.username }} mode=0600

- name : Copy known_hosts in place
  copy: src=ssh/known_hosts dest=/home/{{ admin.username }}/.ssh/known_hosts
          owner={{ admin.username }} group={{ admin.username }} mode=0600

- name: Prevent login with password
  template: src=ssh/sshd_config.j2 dest=/etc/ssh/sshd_config
          owner=root group=root mode=0644
  notify: restart ssh

- name: Create a basic firewall settings file
  template: src=iptables/iptables.firewall.rules.j2 dest=/etc/iptables.firewall.rules
          owner=root group=root mode=0644
  # Firewall gets activated using a separate playbook due to possible SSH port change!
  #notify: activate firewall rules

- name: Create firewall startup script
  copy: src=iptables/firewall_startup.sh dest=/etc/network/if-pre-up.d/firewall
          owner=root group=root mode=0755

- name: Install fail2ban
  apt: pkg=fail2ban state=installed

- name: Create local configuration file for fail2ban
  template: src=fail2ban/jail.local.j2 dest=/etc/fail2ban/jail.local
          owner=root group=root mode=0644
  notify: restart fail2ban

#- name: Install automatic security updates
#  apt: pkg=unattended-upgrades state=installed

#- name: Configure automatic security updates

- name: Install LogWatch to monitor server logs
  apt: pkg={{ item }} state=installed
  with_items:
   - logwatch
   - libdate-manip-perl

- name: Configure LogWatch
  command: logwatch --mailto {{ admin.email }} --output mail --format html --range 'between -7 days and today'
